name: Check CellDeps 
# Every day at midnight (UTC)

on:
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight (UTC)
jobs:
  Check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.5.0
        with:
          node-version: '20'
      - uses: pnpm/action-setup@v3
        name: Install -g pnpm
        with:
          version: 9
          run_install: false
          
      - name: Install dependency
        run: pnpm install

      - name: Check CellDeps
        run: |
          pnpm check:cellDeps
