name: Update CellDeps 
# Every 30 Minutes

on:
  pull_request:
  # schedule:
  #   - cron: '*/30 * * * *'  # Run every 30 minutes

jobs:
  Update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.5.0
        with:
          node-version: '20'
      - uses: pnpm/action-setup@v3
        name: Install -g pnpm
        with:
          version: 9
          run_install: false
          
      - name: Install dependency
        run: pnpm install

      - name: Update CellDeps
        run: |
          pnpm update:cellDeps